---
platform: linux
image_resource:
  type: docker-image
  source: {repository: maven}

inputs:
- name: pipeline-code
- name: pull-request


run:
  path: pipeline-code/pipeline_real/scripts/verify.sh
