---
platform: linux
image_resource:
  type: docker-image
  source: {repository: maven}

inputs:
- name: pipeline-code
- name: source-code

outputs:
- name: cf-deploy-files


run:
  path: pipeline-code/pipeline_real/scripts/package.sh
